<a href="https://colab.research.google.com/github/anamacao/analise_dados/blob/main/dados/Analise_dados_06_combinando_dataframe_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Combinando dataframe

In [1]:
import numpy as np
import pandas as pd

In [2]:
argentina = "https://raw.githubusercontent.com/anamacao/analise_dados/main/dados/MERCOSUL_Argentina_API_ARG_DS2_en_csv_v2_5255054.csv"
brasil = "https://raw.githubusercontent.com/anamacao/analise_dados/main/dados/MERCOSUL_Brasil_API_BRA_DS2_pt_csv_v2_4911136.csv"
uruguai = "https://raw.githubusercontent.com/anamacao/analise_dados/main/dados/MERCOSUL_Uruguai_API_URY_DS2_en_csv_v2_5255430.csv"
paraguai = "https://raw.githubusercontent.com/anamacao/analise_dados/main/dados/MERCOSUL_Paraguai_API_PRY_DS2_en_csv_v2_5213758.csv"

In [3]:
df_brasil = pd.read_csv(brasil)
df_brasil

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,Unnamed: 66
0,Brasil,BRA,Exportações de alta tecnologia (% de exportaçõ...,TX.VAL.TECH.MF.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,1.196972e+01,1.237106e+01,1.448571e+01,1.599996e+01,1.431172e+01,1.474391e+01,1.406646e+01,1.135005e+01,9.001535e+00,NaN
1,Brasil,BRA,Índice de termos de permuta líquida (2000 = 100),TT.PRI.MRCH.XD.WD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.257597e+02,1.214837e+02,1.073474e+02,1.099277e+02,1.162342e+02,1.147659e+02,1.149451e+02,1.156161e+02,NaN,NaN
2,Brasil,BRA,Comércio de mercadorias (% do PIB),TG.VAL.TOTL.GD.ZS,1.603010e+01,1.657218e+01,1.398209e+01,1.242286e+01,1.284599e+01,1.198281e+01,...,1.960630e+01,1.879834e+01,2.037727e+01,1.808620e+01,1.845610e+01,2.215659e+01,2.211577e+01,2.592340e+01,3.203921e+01,NaN
3,Brasil,BRA,"População, total",SP.POP.TOTL,7.309252e+07,7.533001e+07,7.759922e+07,7.991556e+07,8.226279e+07,8.462375e+07,...,2.017218e+08,2.034596e+08,2.051882e+08,2.068596e+08,2.085050e+08,2.101666e+08,2.117829e+08,2.131963e+08,2.143262e+08,NaN
4,Brasil,BRA,Crescimento da população (anual %),SP.POP.GROW,NaN,3.015260e+00,2.967878e+00,2.941316e+00,2.894841e+00,2.829600e+00,...,8.683462e-01,8.578348e-01,8.459926e-01,8.112565e-01,7.922634e-01,7.937682e-01,7.661078e-01,6.651767e-01,5.285905e-01,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,Brasil,BRA,"Remessas pessoais, recebidas (US$ atual)",BX.TRF.PWKR.CD.DT,NaN,NaN,NaN,NaN,NaN,NaN,...,2.717675e+09,2.647909e+09,2.896910e+09,2.739787e+09,2.698771e+09,2.933489e+09,3.213622e+09,3.566219e+09,4.102018e+09,NaN
59,Brasil,BRA,"Investimento estrangeiro direto, ingressos líq...",BX.KLT.DINV.CD.WD,NaN,NaN,NaN,NaN,NaN,NaN,...,7.521103e+10,8.771398e+10,6.473815e+10,7.429463e+10,6.888549e+10,7.816272e+10,6.917441e+10,3.778629e+10,4.643907e+10,NaN
60,Brasil,BRA,Superfície (km²),AG.SRF.TOTL.K2,NaN,8.515770e+06,8.515770e+06,8.515770e+06,8.515770e+06,8.515770e+06,...,8.515770e+06,8.515770e+06,8.515770e+06,8.515770e+06,8.515770e+06,8.515770e+06,8.515770e+06,8.515770e+06,NaN,NaN
61,Brasil,BRA,Área florestal (km²),AG.LND.FRST.K2,NaN,NaN,NaN,NaN,NaN,NaN,...,5.069632e+06,5.054240e+06,5.038848e+06,5.020821e+06,5.000916e+06,4.990514e+06,4.977985e+06,4.966196e+06,NaN,NaN
62,Brasil,BRA,Terra cultivável (% de área terrestre),AG.LND.AGRI.ZS,NaN,1.877918e+01,1.922270e+01,1.966622e+01,2.010974e+01,2.055326e+01,...,2.799625e+01,2.808249e+01,2.816873e+01,2.825497e+01,2.834107e+01,2.834109e+01,2.834109e+01,2.834109e+01,NaN,NaN